# Generated by Django 2.2.4 on 2019-10-25 19:37

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20191025_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='banner_author',
            field=wagtail.core.fields.RichTextField(default='author'),
            preserve_default=False,
        ),
    ]
