# Generated by Django 2.2.4 on 2019-10-28 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmedia', '0003_copy_media_permissions_to_collections'),
        ('home', '0005_homepage_banner_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='featured_podcast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.Media'),
        ),
    ]
