# Generated by Django 2.2.4 on 2019-10-30 11:07

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtailmedia.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20191029_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('card', wagtail.core.blocks.StructBlock([('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('trackno', wagtail.core.blocks.FloatBlock(help_text='Track Number', required=True)), ('title', wagtail.core.blocks.CharBlock(help_text='Episode Title', max_length=40, required=True)), ('track', wagtailmedia.blocks.AbstractMediaChooserBlock(help_text='Upload/Choose audio file', required=True)), ('trackdate', wagtail.core.blocks.DateBlock(help_text='Upload date', required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Upload/Choose Image', required=False))])))]))], blank=True, null=True),
        ),
    ]
